# Generated by Django 4.2.28 on 2026-03-02 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(help_text='Nombre de la marca asociada al registro', max_length=100)),
                ('sucursal', models.CharField(help_text='Nombre de la sucursal', max_length=100)),
                ('aspirante', models.CharField(help_text='Nombre completo del aspirante', max_length=100)),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
                'ordering': ['id'],
            },
        ),
    ]
